name: Docker Build

on:
  push:
    branches-ignore:
      - master

jobs:
  build-ocp-feature:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Fetch external dependencies
      run: make fetch DEPLOYMENT_TYPE=ocp
    - name: Build the Docker image
      run: make build DEPLOYMENT_TYPE=ocp
    - name: Test Docker image
      run: make test DEPLOYMENT_TYPE=ocp
