name: Docker Build

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Fetch external dependencies
      run: make fetch
    - name: Build the Docker image
      run: make build
    - name: Test Docker image
      run: make test
    - name: Login to Docker Registry
      run: docker login -u ${{ secrets.REGISTRY_USERNAME }} -p ${{ secrets.REGISTRY_PASSWORD }}
    - name: Push Docker image
      run: make push
