# generated by terraform

[ignition]
${ignition_node}

[bootstrap]
${bootstrap_node}

[haproxy]
${haproxy_nodes}

[haproxy:vars]
floating_ip=${floating_ip}

[master]
${master_nodes}

[worker]
${worker_nodes}
